### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by haesleinhuepf** [haesleinhuepf/git-bob#382]
Read the file https://github.com/haesleinhuepf/git-bob/blob/main/src/git_bob/_github_utilities.py and let's create a new file src/git_bob/_gitlab_utilities.py which is API-compatible with the github utilities, but uses the gitlab python API instead. But files must have an identical API.

Related to #378 

git-bob solve

**Comment by haesleinhuepf** [comment]
Note to self: Anthropic claude said, our github workflow translated to gitlab ci looks like the following and we should save it into a `.gitlab-ci.yml` file. Note: "gitlab-action" is not implemented yet

```
stages:
  - respond

respond:
  stage: respond
  image: ubuntu:latest
  
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_PIPELINE_SOURCE == "push"
    - if: $CI_PIPELINE_SOURCE == "web"

  before_script:
    - apt-get update && apt-get install -y python3 python3-pip git
    - python3 -m pip install --upgrade pip

  script:
    - echo "Merge Request IID - $CI_MERGE_REQUEST_IID"
    - echo "Project Namespace - $CI_PROJECT_NAMESPACE"
    - echo "Project Name - $CI_PROJECT_NAME"
    - echo "Pipeline ID - $CI_PIPELINE_ID"
    - echo "Job ID - $CI_JOB_ID"
    
    - pip install -e .
    - pip install -r requirements.txt
    
    - |
      git-bob gitlab-action $CI_PROJECT_PATH $CI_MERGE_REQUEST_IID $CI_OPEN_MERGE_REQUESTS_IID

  variables:
    GIT_BOB_AGENT_NAME: "git-bob"
    GIT_BOB_LLM_NAME: "$GIT_BOB_LLM_NAME"
    ANTHROPIC_API_KEY: "$ANTHROPIC_API_KEY"
    GOOGLE_API_KEY: "$GOOGLE_API_KEY"
    OPENAI_API_KEY: "$OPENAI_API_KEY"
    GH_MODELS_API_KEY: "$GH_MODELS_API_KEY"
    KISSKI_API_KEY: "$KISSKI_API_KEY"
    BLABLADOR_API_KEY: "$BLABLADOR_API_KEY"
    GITLAB_API_KEY: "$GITLAB_API_TOKEN"
    GITLAB_PIPELINE_ID: "$CI_PIPELINE_ID"
    TWINE_USERNAME: "$TWINE_USERNAME"
    TWINE_PASSWORD: "$TWINE_PASSWORD"
    SYSTEM_MESSAGE: |
      You are an extremely skilled python developer. Your name is git-bob. You are sometimes called gitlab-ci bot.
      You can solve programming tasks and review code.
      When asked to solve a specific problem, you keep your code changes minimal and only solve the problem at hand.
      You cannot retrieve information from other sources but from gitlab.com.
      Do not claim anything that you don't know.
      In case you are asked to review code, you focus on the quality of the code.
    VISION_SYSTEM_MESSAGE: |
      You are an AI-based vision model with excellent skills when it comes to describing image. When describing an image, you typically explain:
      * What is shown in the image.
      * If the image shows clearly distinct objects in its channels, these structures are listed for each channel individually.
      * You speculate how the image was acquired.
```
